with Interfaces.C; use Interfaces.C;
-- @summary
-- Types used to represent the actual control problem 
-- and the various user-defined parameters. 
--
-- @description
-- These types are used by the problem compiler to describe 
-- the actual control problem and the various user-defined parameters.  
-- That means, these types are hard-coded in the problem compiler implementation.
-- Any change of a type definition requires at least checking 
-- the consequences for the output of the problem compiler.
package Established_Types is

-- -------------------------------------------------------------
-- Every package shall contain the following strings that are       
-- generated by svn automatically (after initial setup by hand)                   
--
   svn_author  : constant String := "$Author: lf1balwe $";
   svn_revision: constant String := "$Revision: 1047 $";
   svn_date    : constant String := "$Date: 2017-03-22 15:21:43 +0100 (Mi, 22. Mär 2017) $";
-- 
-- To enable the mechanism:                                 
-- 1) Run
-- svn propset svn:keywords "Author Rev Date" <name of file> 
-- 2) Copy-Paste to the file the strings
-- svn_author  : constant String := "$Author$";
-- svn_revision: constant String := "$Revision$";
-- svn_date    : constant String := "$Date$";
-- 
-- If a package consists of a body and a specification file
-- then include the strings in the body file. 
-- -------------------------------------------------------------



-- Level 0: Types derived directly from the language

   subtype Float_T              is Double;

   subtype NonNegative_Float_T       is Float_T range 0.0 .. Float_T'Last;

   pragma Warnings(Off, "size clause forces biased representation*");
   type Positive_Integer_T      is range 1 .. 2**32;
   for  Positive_Integer_T'Size use 32; 
   pragma Warnings(On,"size clause forces biased representation*");

   type NonNegative_Integer_T        is range 0 .. 2**32 - 1;
   for  NonNegative_Integer_T'Size use 32; 

   type Float_T_Array        is array (NonNegative_Integer_T range <>) of Float_T;
   -- Auxiliary type to be used in integration formulas
   type Float_T_Array_Access is access all Float_T_Array;
   
-- Level 1: Types being compositions of Level 0-types
-- These types describe mathematical objects

   type Component_Index_T            is new NonNegative_Integer_T; 
   -- It must include the zero to allow for empty arrays.

   type Vector_Float_T               is array (Component_Index_T range <> ) of Float_T;
   type Vector_Float_T_Access        is access all Vector_Float_T;

   type Vector_NonNegative_Float_T        is array (Component_Index_T range <> ) of NonNegative_Float_T;
   type Vector_NonNegative_Float_T_Access is access all Vector_NonNegative_Float_T;
 
   type Vector_Positive_Integer_T        is array (Component_Index_T range <> ) of Positive_Integer_T;
   type Vector_Positive_Integer_T_Access is access all Vector_Positive_Integer_T;

   type Vector_Component_Index_T         is array (Component_Index_T range <> ) of Component_Index_T;
   type Vector_Component_Index_T_Access  is access all Vector_Component_Index_T;

   type Matrix_Float_T               is array (Component_Index_T range <> ,Component_Index_T range <> ) of Float_T;
   type Matrix_Float_T_Access        is access all Matrix_Float_T;
   
-- Level 2i: Types being compositions of Level 0-types and Level 1-types
-- A type of Level 2i describes a mathematical object

   type End_Point_T               is (Lower,Upper);
   type Compact_Hyperinterval_T   is array (End_Point_T) of Vector_Float_T_Access;
   type Compact_Hyperinterval_T_Access    is access all Compact_Hyperinterval_T;

   type Compact_Hyperinterval_T_Array        is array (NonNegative_Integer_T range <>) of Compact_Hyperinterval_T;
   type Compact_Hyperinterval_T_Array_Access is access all Compact_Hyperinterval_T_Array;

-- Level 2ii: Types being compositions of Level 1-types
-- A type of Level 2ii describes an object of control theory

   subtype Time_T                    is Float_T;
   type Time_T_Access                is access all Time_T;
   type State_T                      is new Vector_Float_T;
   type State_T_Access               is access all State_T;
   type Input_T                      is new Vector_Float_T;
   type Input_T_Access               is access all Input_T;

   type State_Radius_T               is new Vector_NonNegative_Float_T;
   type State_Radius_T_Access        is access all State_Radius_T;
   type Input_Radius_T               is new Vector_NonNegative_Float_T;
   type Input_Radius_T_Access        is access all Input_Radius_T;

   type State_Space_Subdivision_T        is new Vector_Positive_Integer_T;
   type State_Space_Subdivision_T_Access is access all State_Space_Subdivision_T;
   type Input_Space_Subdivision_T        is new Vector_Positive_Integer_T;
   type Input_Space_Subdivision_T_Access is access all Input_Space_Subdivision_T;

   type List_of_Component_Index_T        is new Vector_Component_Index_T;
   type List_of_Component_Index_T_Access is access all List_of_Component_Index_T;

   subtype Bounds_of_Measurement_Errors_T           is State_Radius_T;
   type    Bounds_of_Measurement_Errors_T_Access    is access all Bounds_of_Measurement_Errors_T;
   subtype Bounds_of_Dynamic_Uncertainties_T        is State_Radius_T;
   type    Bounds_of_Dynamic_Uncertainties_T_Access is access all Bounds_of_Dynamic_Uncertainties_T;

   subtype Bounds_of_Numerical_Errors_State_T        is State_Radius_T;
   type    Bounds_of_Numerical_Errors_State_T_Access is access all Bounds_of_Numerical_Errors_State_T;

   subtype Bounds_of_Numerical_Errors_Input_T        is Input_Radius_T;
   type    Bounds_of_Numerical_Errors_Input_T_Access is access all Bounds_of_Numerical_Errors_Input_T;
   

-- Level 3:

   type Integration_T              is access procedure (x_out : in out State_T; 
                                                        t     : in Time_T; 
                                                        x0    : in State_T; 
                                                        u     : in Input_T);
   -- Type of numerical integration formula for the solution at time t of x_out' = f(x_out,u), x_out(0)=x0.
   -- x_out: The result of the integration
   -- t    : The time parameter
   -- x0   : The initial value
   -- u    : The control value
   -- See dynamics_specification_parameters.ads for the assumptions on the arguments x_out, t, x0 and u.
   type Growth_Bound_Integration_T is access procedure (x_out : in out State_Radius_T; 
                                                        t     : in Time_T; 
                                                        r0    : in State_Radius_T; 
                                                        L     : in Vector_Float_T; 
                                                        w     : in Bounds_of_Dynamic_Uncertainties_T);
   -- Type of numerical integration formula for the solution at time t of x_out' = L*x_out + w, x_out(0)=r0
   -- x_out: The result of the integration.
   -- t    : The time parameter
   -- r0   : The initial value
   -- L    : The Lipschitz-Matrix as an array row-by-row
   -- w    : The bound of the dynamic uncertainties.
   -- See dynamics_specification_parameters.ads for the assumptions on the arguments x_out, t, r0, L and w.
   
   type Problem_T is record
      State_Space_Dimension : Component_Index_T;
      -- The state space dimension
      Input_Space_Dimension : Component_Index_T;
      -- The input space dimension
      xmin                : State_T_Access;
      -- The hyperinterval [[xmin,xmax]] is the union of the compact cells
      xmax                : State_T_Access;
      -- The hyperinterval [[xmin,xmax]] is the union of the compact cells
      umin                : Input_T_Access;
      -- The hyperinterval [[umin,umax]] is the continuous input set
      umax                : Input_T_Access;
      -- The hyperinterval [[umin,umax]] is the continuous input set
      List_of_periodic_components    : List_of_Component_Index_T_Access;
      -- The components in which the right hand side possesses a period
      List_of_nonperiodic_components : List_of_Component_Index_T_Access;
      -- The components in which the right hand side does not possess a period
      Initial_State_Space_Subdivision : State_Space_Subdivision_T_Access;
      -- User-defined discretization of the state space
      Initial_Input_Space_Subdivision : Input_Space_Subdivision_T_Access;
      -- User-defined discretization of the input space
      Bounds_of_Dynamic_Uncertainties  : Bounds_of_Dynamic_Uncertainties_T_Access;
      -- The vector with the bound on the dynamic uncertainties
      Bounds_of_Measurement_Errors : Bounds_of_Measurement_Errors_T_Access;
      -- The vector with the bound on the measurement errors
      Sampling_Time : Time_T ;
      -- The sampling time
      Initial_State_Set  : Compact_Hyperinterval_T_Array_Access;
      -- The initial set of the reach-avoid specification
      Target_State_Set   : Compact_Hyperinterval_T_Array_Access;
      -- The target set of the reach-avoid specification
      Obstacle_State_Set : Compact_Hyperinterval_T_Array_Access;
      -- The obstacle set of the reach-avoid specificaition
      General_Solution_Formula  : Integration_T;
      -- The integration formula for integrating the continuous-time dynamics
      Growth_Bound_Formula : Growth_Bound_Integration_T;
      -- The approximation formula for the growth bounds
     
      Apriori_Enclosure                                   : Compact_Hyperinterval_T_Access;
      Apriori_Enclosure_Backward_with_DynamicUncertanties : Compact_Hyperinterval_T_Access;
      Apriori_Enclosure_Backward_wout_DynamicUncertanties : Compact_Hyperinterval_T_Access;
      
      -- The apriori enclosure for continuous-time dynamics (it is a uniform one in the state and control input) 
      Apriori_Enclosure_Growth_Bound : Compact_Hyperinterval_T_Access;
      Apriori_Enclosure_Growth_Bound_Backward_with_DynamicUncertanties : Compact_Hyperinterval_T_Access;
      Apriori_Enclosure_Growth_Bound_Backward_wout_DynamicUncertanties : Compact_Hyperinterval_T_Access;
      -- The apriori enclosure for the growth bounds (it is a uniform one in the state and control input) 
      Rounded_Initial_State_Radius                  : State_Radius_T_Access;
      -- See Programmer's Manual; 
      Bounds_of_Lipschitz_Matrices                  : Vector_Float_T_Access ;
      -- See Programmer's Manual; 
      Bounds_of_Input_Value_Rounding_Error          : Bounds_of_Numerical_Errors_Input_T_Access;
      -- See Programmer's Manual; 
      Bounds_of_Approximation_Error_of_General_Solution  : Bounds_of_Numerical_Errors_State_T_Access;
      -- Bound on the distance between the (mathematical) solution to x'=f(x,u) and its approximation formula
      Bounds_of_Rounding_Error_of_General_Solution       : Bounds_of_Numerical_Errors_State_T_Access;
      -- Bound on the distance between previous approximation formula and its floating-point implementation
      Bounds_of_Approximation_Error_of_Growth_Bound : Bounds_of_Numerical_Errors_State_T_Access;
      -- Bound on the distance between the (mathematical) solution to r'=Lr + w and its approximation formula
      Bounds_of_Rounding_Error_of_Growth_Bound      : Bounds_of_Numerical_Errors_State_T_Access;
      -- Bound on the distance between previous approximation formula and its floating-point implementation
      Bounds_of_Summation_Error_Growth_Bound     : Bounds_of_Numerical_Errors_State_T_Access;
      --  Bound on the rounding error when adding radii
      Bounds_of_Summation_Error_General_Solution : Bounds_of_Numerical_Errors_State_T_Access;
      --  Bound on the rounding error when adding center of cell to a radius
      Bounds_of_Overapproximation_Rounding_Error    : Bounds_of_Numerical_Errors_State_T_Access;
      -- See Programmer's Manual; 
      Bounds_of_Overapproximation_Radius            : Bounds_of_Numerical_Errors_State_T_Access;
      -- See Programmer's Manual; 
   end record;

   type Problem_T_Access is access all Problem_T;

 

end Established_Types;
