with Ada.Containers;
package body Cell_Cover is

-- -------------------------------------------------------------
-- Every package shall contain the following strings that are       
-- generated by svn automatically (after initial setup by hand)                   
--
   svn_author  : constant String := "$Author: lf3eelma $";
   svn_revision: constant String := "$Revision: 2395 $";
   svn_date    : constant String := "$Date: 2021-10-25 23:29:03 +0200 (Mo, 25 Okt 2021) $";
-- 
-- To enable the mechanism:                                 
-- 1) Run
-- svn propset svn:keywords "Author Rev Date" <name of file> 
-- 2) Copy-Paste to the file the strings
-- svn_author  : constant String := "$Author: lf3eelma $";
-- svn_revision: constant String := "$Revision: 2395 $";
-- svn_date    : constant String := "$Date: 2021-10-25 23:29:03 +0200 (Mo, 25 Okt 2021) $";
-- 
-- If a package consists of a body and a specification file
-- then include the strings in the body file. 
-- -------------------------------------------------------------


-- --------------------------------
-- Install ------------------------
-- --------------------------------

function Install(P : in Problem_T) return Cell_Cover_T is 
 subdivision : BasicGrid.Vector_of_Coordinate_Index (P.Initial_State_Space_Subdivision'Range);
 Cover : Cell_Cover_T;
begin
  for i in P.Initial_State_Space_Subdivision'Range loop
   subdivision(i):=BasicGrid.Unsigned_Coordinate_Index_Type(P.Initial_State_Space_Subdivision(i));
  end loop;
   CellGrid.init(grid        => CellGrid.Grid_on_Manifold_Record(Cover),
                 subdivision => subdivision,
                 xmin        => P.xmin.all,
                 xmax        => P.xmax.all,
                 Periods     => P.List_of_periodic_components.all,
                 NoPeriods   => P.List_of_nonperiodic_components.all);
   CellGrid.init(CellGrid.Grid_on_Manifold_Record(Cover),P.Bounds_of_Overapproximation_Rounding_Error);
   return Cover;
 end Install;

-- --------------------------------
-- Get_First_Index ----------------
-- --------------------------------

function Get_First_Index(Cover : Cell_Cover_T) return Cell_Index_T
is
begin
 return 0;
end Get_First_Index;

-- --------------------------------
-- Get_Last_Index -----------------
-- --------------------------------

function Get_Last_Index(Cover : Cell_Cover_T) return Cell_Index_T
is
begin
 return BasicGrid.get_last_used_index(BasicGrid.Grid_Record(Cover));
end Get_Last_Index;

-- --------------------------------
-- Get_Center_Of_Cell -------------
-- --------------------------------

procedure Get_Center_Of_Cell(center: in out State_T; idx : in Cell_Index_T; Cover : in Cell_Cover_T)
is
begin
  CellGrid.get_gridpoint(center,idx,CellGrid.Grid_on_Manifold_Record(cover));
end get_center_of_cell;

-- --------------------------------
-- Is_Index_Cell ------------------
-- --------------------------------

function Is_Index_Cell(idx: Cell_Index_T; Cover : Cell_Cover_T) return Boolean
is
 use BasicGrid;
begin
 if idx <= get_last_used_index(Cover) and idx>= Get_First_Index(Cover) then return True;
 else return False;
 end if;
end Is_Index_Cell;

-- --------------------------------
-- Save_Cell_To_Container ------------------
-- --------------------------------  
 
procedure Save_Cell_To_Container(container : in out Dynamic_Cell_Container; idx : Cell_Index_T) is
      
begin
 CellGrid.save_index(container,idx);      
end Save_Cell_To_Container;
   
   
  -- --------------------------------
-- Is_container_allocated ------------------
-- --------------------------------   
   
function Is_container_allocated (container : in Dynamic_Cell_Container) return Boolean is   
begin
 return CellGrid.Is_container_allocated(container);   
end Is_container_allocated;
   
   -- --------------------------------
-- Deallocate_container ------------------
-- --------------------------------   
   
procedure Deallocate_container (container : in out Dynamic_Cell_Container) is      
begin
 CellGrid.Deallocate_container(container); 
end Deallocate_container;
 
   -- --------------------------------
-- Empty_container ------------------
-- --------------------------------  
  
procedure Empty_container (container : in out Dynamic_Cell_Container) is 
begin   
 CellGrid.Empty_container(container);   
end Empty_container;

      
   -- --------------------------------
-- Deallocate_Dynamic_Array_of_Cell_Index_T ---
-- --------------------------------  

procedure Deallocate_Dynamic_Array_of_Cell_Index_T (dynamic_cell_array: in out Dynamic_Array_of_Cell_Index_T) is       
begin    
 CellGrid.free_Cell_array(dynamic_cell_array);     
end Deallocate_Dynamic_Array_of_Cell_Index_T;
   
   
   
    -- --------------------------------
-- Save_Overapproximation_To_Container ------
-- --------------------------------    
   
procedure Save_Overapproximation_To_Container(container : in out Dynamic_Overapproximation_Container; oa : Abstract_Reachable_Set_Geometry_T) is  
begin      
 CellGrid.save_index(container,oa);     
end Save_Overapproximation_To_Container;
 
    -- --------------------------------
-- Is_container_allocated ------
-- --------------------------------    
   
function Is_container_allocated (container : in  Dynamic_Overapproximation_Container) return Boolean is      
begin
 return CellGrid.Is_container_allocated(container);     
end Is_container_allocated;
   
     -- --------------------------------
-- Deallocate_container ------
-- --------------------------------    
   
procedure Deallocate_container (container : in out Dynamic_Overapproximation_Container) is      
begin      
 CellGrid.Deallocate_container(container);      
end Deallocate_container;
 
     -- --------------------------------
-- Deallocate_container ------
-- --------------------------------    
  
procedure Empty_container (container : in out Dynamic_Overapproximation_Container) is      
begin      
 CellGrid.Empty_container(container);      
end Empty_container; 
   
   
   
end Cell_Cover;
