with Interfaces.C;  use Interfaces.C;
with Established_Types; use Established_Types;

package body math_functions is

-- -------------------------------------------------------------
-- Every package shall contain the following strings that are       
-- generated by svn automatically (after initial setup by hand)                   
--
   svn_authomr  : constant String := "$Author: Weber_A $";
   svn_revision: constant String := "$Revision: 2392 $";
   svn_date    : constant String := "$Date: 2021-10-25 11:30:20 +0200 (Mo, 25 Okt 2021) $";
-- 
-- To enable the mechanism:                                 
-- 1) Run
-- svn propset svn:keywords "Author Rev Date" <name of file> 
-- 2) Copy-Paste to the file the strings
-- svn_author  : constant String := "$Author: Weber_A $";
-- svn_revision: constant String := "$Revision: 2392 $";
-- svn_date    : constant String := "$Date: 2021-10-25 11:30:20 +0200 (Mo, 25 Okt 2021) $";
-- 
-- If a package consists of a body and a specification file
-- then include the strings in the body file. 
-- -------------------------------------------------------------

   function ABSLib_atan (x : in Float_T) return Float_T
   is 
     function atan_C (x : in Float_T) return Float_T;
     pragma Import (C, atan_C, "ABS_atan");
   begin
   return atan_C(x);
   end ABSLib_atan;
   
   function ABSLib_cos (x : in Float_T) return Float_T
   is 
     function cos_C (x : in Float_T) return Float_T;
     pragma Import (C, cos_C, "ABS_cos");
   begin
   return cos_C(x);
   end ABSLib_cos;
   
   function ABSLib_cosh (x : in Float_T) return Float_T
   is 
     function cosh_C (x : in Float_T) return Float_T;
     pragma Import (C, cosh_C, "ABS_cosh");
   begin
   return cosh_C(x);
   end ABSLib_cosh;
   
   function ABSLib_exp (x : in Float_T) return Float_T
   is 
     function exp_C (x : in Float_T) return Float_T;
     pragma Import (C, exp_C, "ABS_exp");
   begin
   return exp_C(x);
   end ABSLib_exp;
   
   function ABSLib_log (x : in Float_T) return Float_T
   is 
     function ABS_log (x : in Float_T) return Float_T;
     pragma Import (C, ABS_log, "ABS_log");
   begin
   return ABS_log(x);
   end ABSLib_log;
   
   function ABSLib_sin (x : in Float_T) return Float_T
   is 
     function sin_C (x : in Float_T) return Float_T;
     pragma Import (C, sin_C, "ABS_sin");
   begin
   return sin_C(x);
   end ABSLib_sin;
   
   function ABSLib_sinh (x : in Float_T) return Float_T
   is 
     function sinh_C (x : in Float_T) return Float_T;
     pragma Import (C, sinh_C, "ABS_sinh");
   begin
   return sinh_C(x);
   end ABSLib_sinh;
   
   function ABSLib_sqrt (x : in Float_T) return Float_T
   is 
   begin
   return GenElFun_64.sqrt(x); -- Square root is formally correct
   end ABSLib_sqrt;
   
   function ABSLib_tan (x : in Float_T) return Float_T
   is 
     function tan_C (x : in Float_T) return Float_T;
     pragma Import (C, tan_C, "ABS_tan");
   begin
   return tan_C(x);
   end ABSLib_tan;

end math_functions;
